### ISSUE TITLE
[BUG]OOC Dice Rolls Don't Roll

### ISSUE THREAD

**Issue by Grubleafeater** [CherpChat/IssueBoard#13]
**Describe the bug**
/xdy doesn't work when ooc is on
**To Reproduce**
Turn ooc on in a chat
send /3d6 or any other valid dice expression

**Expected behavior**
for the dice roller to work

**Screenshots**
![image](https://user-images.githubusercontent.com/42578905/106950318-38764980-66fc-11eb-9d1d-8ebfca8f54a7.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version 88.0.4324.104

**Comment by two-keys** [comment]
Fixed for 3.2.
