### ISSUE TITLE
[FEATURE]Orientation tags?

### ISSUE THREAD

**Issue by pixxelatedice** [CherpChat/IssueBoard#17]
I was wondering if orientation/sexuality tags could be made a thing? Like gay/lesbian, straight, bisexual etc. I would filter out the gender I am not looking for but that removes prompts with both genders tagged and takes out a huge market.

**Comment by two-keys** [comment]
We've decided against adding sexuality orientation/tags to the default checkboxes / fields. If you want to add a sexuality tag yourself, I would recommend adding it as a characteristic. Alternatively, you can add a pairing identifier (such as 'M/M', 'M/F', 'F/F', etc) as a Misc Tag.
