### ISSUE TITLE
[FEATURE] Chat Info Ease of Use

### ISSUE THREAD

**Issue by theakemi** [CherpChat/IssueBoard#18]
**Is your feature request related to a problem? Please describe.**
Whenever I want to quickly rename chats, I have to click on the chat and then go to chat info.

**Describe the solution you'd like**
I think Cherubplay had it, but a way to just go straight to chat info from the 'your chat' screen.

**Describe alternatives you've considered**
The alternative is clicking on the chat and going to info which doesn't take very long but it could still be simpler. I feel like it should be relatively easy to implement as well.

**Additional context**
I made a small mockup of what I mean. Just clicking the chat info button to get to the chat info immediately would make renaming a bunch of chats at once much easier.

![image](https://user-images.githubusercontent.com/79276548/108399047-9da85f80-7211-11eb-9cc7-d1a301683da1.png)

**Comment by two-keys** [comment]
Now implemented in 3.2.
