### ISSUE TITLE
Improve Dropdown Menu Aesthetic[FEATURE]

### ISSUE THREAD

**Issue by zaggies** [CherpChat/IssueBoard#28]
I use Cherp on at least 125% zoom and the directory/profile dropdown links overlap onto the ads. If an adblocker is on or I'm zoomed in further, these dropdown links also start to disappear under posts, meaning I can't access my whitelist unless I zoom all the way out to put the search/links onto the side of the page where they belong.

Sort of preferred it when the dropdown wasn't a thing, personally, but I can see why others might like the cleaner look it gives, so I'm not really sure what the solution is here.

![image](https://user-images.githubusercontent.com/82347253/114326230-d4a83c80-9b01-11eb-9c91-4e6a9db2d714.png)
![image](https://user-images.githubusercontent.com/82347253/114326247-ebe72a00-9b01-11eb-9258-df36e920f464.png)

**Comment by two-keys** [comment]
Oh yeah. Fixed this.
