### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nicoboo2t** [CherpChat/IssueBoard#33]
**Describe the bug**
Wrote a prompt and the option for delete or bump is gone, completely. This was a prompt with no starter. It has been a day since I created the prompt. 

**To Reproduce**
1. Go to my prompts
2. Click on create new
3. Finish prompt
4. No delete or bump button

**Expected behavior**
Usually a button that says “delete” or  “bump” at the appropriate time 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro 
 - iOS
 - Chrome
![F5B0EB5D-82A3-4C3D-8337-391F625515CF](https://user-images.githubusercontent.com/83923008/117584424-bfeba400-b0c1-11eb-8d89-9209f119f65d.jpeg)

 

**Additional context**

**Comment by two-keys** [comment]
Prompts display the delete button five days after they are created or bumped, alongside the bump button. New prompts won't display either, but can be drafted if you wish to make them invisible in the meantime.

**Comment by two-keys** [comment]
No updates since this was posted- going to assume it's probably fine now. If I was wrong, feel free to reopen this!
