### ISSUE TITLE
[BUG] no bump button

### ISSUE THREAD

**Issue by symphothy** [CherpChat/IssueBoard#36]
disregard, it's there now

**Describe the bug**
no bump button available on my prompts page

**To Reproduce**
1. Go to 'Directory'
2. Click on 'My Prompts'
3. Scroll down to 'prompts and bottom of the page'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [not sure]
 - Browser [Chrome]
 - Version [assuming latest version]

**Smartphone (please complete the following information):**
 - Device: [Galaxy S20 FE]
 - OS: [not sure]
 - Browser [Chrome]
 - Version [Latest]

**Additional context**
Thought that maybe it wasn't available on mobile, just checked on desktop and it isn't there either

**Comment by two-keys** [comment]
It takes five days for a bump button to appear on a given prompt, assuming the global timer is also fine.

Glad it showed up for you in the end!
