### ISSUE TITLE
[FEATURE] Labels for chats

### ISSUE THREAD

**Issue by keburdo** [CherpChat/IssueBoard#4]
Labels for chats existed on Cherubplay. Similar to how there is an unanswered tab, unread, ended, we could be able to label our own chats with things like fandoms so that you can look at a list of all your chats in a certain category

People could try to do this through titles/descriptions and then using the find by feature in the browser but that is especially unhelpful when you have them sparsely spread over multiple pages.

![image](https://user-images.githubusercontent.com/76589736/103137001-087b6580-46bd-11eb-83ab-ae5edb6677b0.png)

**Comment by hecksadecimal** [comment]
You've ignored most of the template. Correct it, please.
This issue will stay closed until then.
