### ISSUE TITLE
[BUG] Escape Characters Result in Failure to Send Post

### ISSUE THREAD

**Issue by RezzyRez** [CherpChat/IssueBoard#42]
**Describe the bug**

Using escape characters at the start of a reply causes the reply to not send until removed.

**To Reproduce**
1. Go to 'Your Chats'
2. Click on 'Any Chat'
3. Scroll down to 'Send' / Attempt to Send

**Expected behavior**

Despite use of escape characters [/ or //] at the beginning of the reply for the reply to still send as opposed to breaking the page and requiring a refresh and removal of the characters.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 89.0.2

**Smartphone (please complete the following information):**
 - Device: LG V40
 - OS: Android
 - Browser: Firefox 
 - Version: 89.1.1

**Additional context**
This happens regardless of browser and mobile vs desktop as it is focused around the presence of escape characters.

**Comment by two-keys** [comment]
Fixed in dev build.
