### ISSUE TITLE
[BUG] Tags don't search right after 3.4

### ISSUE THREAD

**Issue by pocketed-pants** [CherpChat/IssueBoard#46]
**Describe the bug**
Hey, unsure if this has been mentioned already. After the 3.4 update, clicking on a tag in the "Looking For" section links to a directory where the tag is "Playing As" instead. Fandom, character name, and characteristics are all affected.

**To Reproduce**
1. Click on a tag to search by "Character/Fandom/etc. Wanted"
2. Look up in the address bar to see you are searching by character instead of character wanted

**Expected behavior**
Clicking on a "Character Wanted" tag takes me to a search for characters wanted, not "Playing As".

**Screenshots**
N/A, I think?

**Desktop (please complete the following information):**
 I haven't checked to see if this works on my desktop.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8+
 - OS: Android Version 9
 - Browser: Opera
 - Version: 64.2.3283.60128

**Additional context**
N/A

**Comment by two-keys** [comment]
Fixed in 3.4.1
