### ISSUE TITLE
[BUG] Dice Roller Broken

### ISSUE THREAD

**Issue by LuxLoser** [CherpChat/IssueBoard#48]
**Bug:** Attempting to send a message to roll dice results in the message not sending at all and the "Send" button being greyed out until I refresh.

**To Reproduce**
1. Go into a chat
2. Go to the message box
3. Type a dice roller command (e.g. /2d6+1 or /1d8)

**Expected behavior**
The site should present a system message where it displays what dice I had rolled and the numerical outcome.

**Screenshots**
See Attachment
![DiceRollerBug](https://user-images.githubusercontent.com/34172226/127755667-bc59db24-0c6d-410e-b384-c204b76afeca.PNG)

**Desktop:**
 - OS: Windows 10
 - Browser Firefox 
 - Version 90.0.2

**Smartphone:**
 - Device: iPhone SE 2020
 - OS: iOS ver 14.4.2
 - Browser: Chrome
 - Version 92.0.4515.90

**Additional context**
Attempted to use both on my mobile device and desktop. I can confirm based on chat history that it was functional prior to the most recent update.

**Comment by two-keys** [comment]
Weirdddd. Does `/test` work?

**Comment by LuxLoser** [comment]
Yes! And it responds immediately. 

J. in the Discord attempted it and posted this screenshot as well.

![](https://cdn.discordapp.com/attachments/590200481822015511/871194071090208819/Screenshot_20210731-205401-448.png)

**Comment by two-keys** [comment]
Fixed.
