### ISSUE TITLE
[BUG] Answered/Unanswered Pagination

### ISSUE THREAD

**Issue by CarpeVerpa** [CherpChat/IssueBoard#49]
**Describe the bug**
When searching through answered and unanswered chats, attempting to go to a new page results in returning to all chats, rather than simply answered or unanswered ones.

**To Reproduce**
1. Navigate to Your Chats
2. Click on "Answered" or "Unanswered"
3. Click on a number or arrow for a new page of chats

**Expected behavior**
Listed chats should remain filtered as answered or unanswered, rather than showing all chats once again

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 9
 - OS: Android 11
 - Browser Chrome
 - Version 92.0.4515.115

**Additional context**

**Comment by two-keys** [comment]
Ah, yeah. I see what's up- this is fixable. It'll need another rebuild/site downtime, though, so I think it's probably best to hold off on pushing the fix until we get a few more bugs fixed in addition.

**Comment by two-keys** [comment]
Fixed in the upcoming/next update.
