### ISSUE TITLE
[BUG] Bumping doesn't seem to work

### ISSUE THREAD

**Issue by halalsala** [CherpChat/IssueBoard#6]
Whenever the five day limit has passed on some ads I've written, it always looks like I've bumped it, but when I check, it is still in the same position and hasn't actually bumped at all.

 - OS: Windows 10
 - Browser: Brave
 - Version 1.18.78 Chromium: 87.0.4280.141

**Comment by hecksadecimal** [comment]
You've ignored most of the template. Correct it, please.
This issue will stay closed until then.
