### ISSUE TITLE
[BUG] [3.1] Answering prompt produces blank "unknown" chat

### ISSUE THREAD

**Issue by bitchlord** [CherpChat/IssueBoard#7]
**Describe the bug**
Answering a prompt greys out the "answer" button, doesn't open the chat, adds "unknown" chat to chat list. Unsure if the other person's in the chat at all or sees the same thing, will report back on this later.

**To Reproduce**
1. Perform a multi-tag search
2. Click "Answer" on a prompt
3. Receive unexpected behavior (chat doesn't open in same tab)
4. Check list of chats, observe unexpected chat behavior

**Expected behavior**
After clicking "Answer", chat should have opened in the same tab. The list of chats should have had a chat starting with the prompt added to it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 84.0.2

**Comment by two-keys** [comment]
Related to https://github.com/CherpChat/IssueBoard/issues/2 . Closing to consolidate this there.
